"""baseline existing schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-23 20:39:44.460247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_replacements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source'),
    sqlite_autoincrement=True
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'user'"), nullable=False),
    sa.Column('password_hash', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('password_salt', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('password_iterations', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('is_default', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')"),
    sa.CheckConstraint('is_default IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bgm_tracks',
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('duration', sa.REAL(), server_default=sa.text("0"), nullable=False),
    sa.Column('file_size', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bgm_tracks_user', 'bgm_tracks', ['user_id'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('creator_username', sa.Text(), nullable=False),
    sa.Column('creator_display_name', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('generation_type', sa.Text(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extra_info_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('artifacts_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('failed_count >= 0'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100'),
    sa.CheckConstraint('requested_count >= 1'),
    sa.CheckConstraint('success_count >= 0'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generation_tasks_status', 'generation_tasks', ['user_id', 'status'], unique=False)
    op.create_index('idx_generation_tasks_user_created', 'generation_tasks', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_generation_tasks_user_type', 'generation_tasks', ['user_id', 'task_type', 'generation_type'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_sessions_token_hash', 'sessions', ['token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('setting_name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('value_type', sa.Text(), server_default=sa.text("'string'"), nullable=False),
    sa.Column('is_secret', sa.Integer(), server_default=sa.text("0"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('is_secret IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'namespace', 'setting_name'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_settings_user_namespace', 'settings', ['user_id', 'namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_settings_user_namespace', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_token_hash', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_generation_tasks_user_type', table_name='generation_tasks')
    op.drop_index('idx_generation_tasks_user_created', table_name='generation_tasks')
    op.drop_index('idx_generation_tasks_status', table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index('idx_bgm_tracks_user', table_name='bgm_tracks')
    op.drop_table('bgm_tracks')
    op.drop_table('users')
    op.drop_table('subtitle_replacements')
    # ### end Alembic commands ###
